<?php
    echo" <nav>
        <div class=\"topnav\">
            <div class=\"topnav-left\">
                <a href=\"index.php\" class=\"active\">Home</a>
                <a href=\"enquire.php\">Enquiry</a>
            </div>   
            <div class=\"topnav-center\">                    
                <a href=\"product.php\">Products</a>
            </div>
            <div class=\"topnav-right\">
                <a href=\"about.php\">About Us</a>
                <a href=\"enhancements3.html\">Enhancements</a>
            </div>      
        </div>        
    </nav>
    <hr />";
?>